language: android
sudo: required
jdk: oraclejdk8
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

git:
  depth: false

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

stages:
  - name: verify-pr
    if: branch != master
  - name: master-build
    if: branch = master

jobs:
  include:
    - stage: verify-pr
      script: echo "verify-pr 1"
    - stage: verify-pr
      script: echo "verify-pr 2"
    - stage: master-build
      script: echo "verify-pr2 1"
    - stage: master-build
      script: echo "verify-pr2 2"