language: android
sudo: required
jdk: oraclejdk8
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

git:
  depth: false

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

stages:
  - name: verify-pr
    if: head_branch != master
  - name: master-build
    if: head_branch = master

jobs:
  include:
    - stage: verify-pr
      name: compare-apk
      script: bash ./scripts/setup.sh &&
        sh ./scripts/build_release_apk.sh &&
        bash ./scripts/download_master_apk.sh &&
        bundle install && bundle exec danger --new-comment --dangerfile=compare-apk.danger
    - stage: verify-pr
      name: lint
      script: bash ./scripts/setup.sh &&
        ./gradlew :app:lintDebug &&
        bundle install && bundle exec danger --new-comment --dangerfile=lint.danger
    - stage: verify-pr
      name: test-spotless
      script: bash ./scripts/setup.sh &&
      ./gradlew testDebugUnitTest spotlessCheck
    - stage: verify-pr
      name: dynamic-build22
      script: bash ./scripts/setup.sh &&
        ./gradlew :app:bundleDebug -Pdynamic &&
        ./gradlew :app:bundleDebug -Pdynamic -Pexclude=".*"
    - stage: master-build
      name: upload-apk
      script: bash ./scripts/setup.sh &&
        && sh ./scripts/build_release_apk.sh
        && bash ./scripts/upload_master_apk.sh