version: 2.1

executors:
  android_executor:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/fera

commands:
  init:
    description: "Initialize project"
    steps:
      - checkout
      - run:
          name: Initialize
          command: bash ./scripts/setup.sh

jobs:
  compare-apk:
    executor: android_executor
    steps:
      - init
      - run:
          name: Build release apk
          command: sh ./scripts/build_release_apk.sh
          no_output_timeout: 10m
      - run:
          name: Download master apk
          command: bash ./scripts/download_master_apk.sh
      - store_artifacts:
          path: build/universal.apk
          destination: universal.apk
      - store_artifacts:
          path: build/master.apk
          destination: master.apk
      - run:
          name: Danger apk compare
          command: bundle install && bundle exec danger --new-comment --dangerfile=compare-apk.danger
  lint:
    executor: android_executor
    steps:
      - init
      - run:
          name: Lint
          command: ./gradlew :app:lintDebug
          no_output_timeout: 10m
      - run:
          name: Danger lint
          command: bundle install && bundle exec danger --new-comment --dangerfile=lint.danger
      - store_artifacts:
          path: app/build/reports/lint-results-debug.html
          destination: app-lint-results-debug.html
      - store_artifacts:
          path: core/build/reports/lint-results-debug.html
          destination: core-lint-results-debug.html
      - store_artifacts:
          path: home/build/reports/lint-results-debug.html
          destination: home-lint-results-debug.html
  test-spotless:
    executor: android_executor
    steps:
      - init
      - run:
          name: Test spotless
          command: ./gradlew testDebugUnitTest spotlessCheck
          no_output_timeout: 10m
  dynamic-build:
    executor: android_executor
    steps:
      - init
      - run:
          name: Dynamic build include all modules
          command: ./gradlew :app:bundleDebug -Pdynamic
          no_output_timeout: 10m
      - run:
          name: Dynamic build exclude all modules
          command: ./gradlew :app:bundleDebug -Pdynamic -Pexclude=".*"
          no_output_timeout: 10m
  verify-pull-request:
    executor: android_executor
    steps:
      - init
      - run:
          name: Build release apk
          command: sh ./scripts/build_release_apk.sh
          no_output_timeout: 25m
      - run:
          name: Download master apk
          command: bash ./scripts/download_master_apk.sh
      - store_artifacts:
          path: build/universal.apk
          destination: universal.apk
      - store_artifacts:
          path: build/master.apk
          destination: master.apk
      - run:
          name: Danger apk compare
          command: bundle install && bundle exec danger --new-comment --dangerfile=compare-apk.danger
      - run:
          name: Lint test spotless
          command: ./gradlew testDebugUnitTest lintDebug spotlessCheck
          no_output_timeout: 25m
      - run:
          name: Danger lint
          command: bundle exec danger --new-comment --dangerfile=lint.danger
      - store_artifacts:
          path: app/build/reports/lint-results-debug.html
          destination: app-lint-results-debug.html
      - store_artifacts:
          path: core/build/reports/lint-results-debug.html
          destination: core-lint-results-debug.html
      - store_artifacts:
          path: home/build/reports/lint-results-debug.html
          destination: home-lint-results-debug.html
      - run:
          name: Dynamic build include all modules
          command: ./gradlew :app:bundleDebug -Pdynamic --offline
          no_output_timeout: 25m
      - run:
          name: Dynamic build exclude all modules
          command: ./gradlew :app:bundleDebug -Pdynamic -Pexclude=".*" --offline
          no_output_timeout: 25m
  upload-apk:
    executor: android_executor
    steps:
      - checkout
      - run:
          name: Initialize
          command: bash ./scripts/setup.sh
      - run:
          name: Build release apk
          command: sh ./scripts/build_release_apk.sh
          no_output_timeout: 30m
      - run:
          name: Upload apk
          command: bash ./scripts/upload_master_apk.sh
      - store_artifacts:
          path: ./build/universal.apk
          destination: universal.apk

workflows:
  version: 2
  #  pull-request-flow:
  #    jobs:
  #      - compare-apk:
  #          filters:
  #            branches:
  #              ignore:
  #                - master
  #      - lint:
  #          filters:
  #            branches:
  #              ignore:
  #                - master
  #      - test-spotless:
  #          filters:
  #            branches:
  #              ignore:
  #                - master
  #      - dynamic-build:
  #          filters:
  #            branches:
  #              ignore:
  #                - master
  #      - verify-pull-request:
  #          filters:
  #            branches:
  #              ignore:
  #                - master

  #  master-flow:
  #    jobs:
  #      - upload-apk:
  #          filters:
  #            branches:
  #              only:
  #                - master

#  benchmark-verify-pull-request-v6:
#    jobs:
#      - compare-apk:
#          filters:
#            branches:
#              ignore:
#                - master
#      - lint:
#          filters:
#            branches:
#              ignore:
#                - master
#      - test-spotless:
#          filters:
#            branches:
#              ignore:
#                - master
#      - dynamic-build:
#          filters:
#            branches:
#              ignore:
#                - master

